default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  socket: <%= ENV['MYSQL_UNIX_PORT'] || "/tmp/mysql.sock" %>

development:
  <<: *default
  database: fanfic_dev

test:
  <<: *default
  database: fanfic_test


production:
  <<: *default
  database: fanfic_prod
  username: <%= ENV['FANFIC_DATABASE_USERNAME'] %>
  password: <%= ENV['FANFIC_DATABASE_PASSWORD'] %>
